title: Sajjad Zamani
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

description: >- # this means to ignore newlines until "baseurl:"
author:
  name: Sajjad Zamani

show_excerpts: false

minima:
  social_links:
    github: sjjz

header_pages:
  - gallery/index.html
  - about.md

# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
